### ISSUE TITLE
manifest parse error(s): The manifest file at https://github.com/IBM-Swift/CCryptoSSL.git (0.1.5) is empty

### ISSUE THREAD

**Issue by arkeo01** [IBM-Swift/OpenSSL#12]
Kindly fix this error...

**Comment by arkeo01** [comment]
import PackageDescription

var deps: [Package.Dependency] = [
	.package(url: "https://github.com/IBM-Swift/Kitura.git", from: Version("1.0.2")),
	.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: Version("1.7.1")),
	.package(url: "https://github.com/IBM-Swift/Kitura-WebSocket", from: Version("1.0.0")),
]

**Comment by ianpartridge** [comment]
Can you supply a complete `Package.swift`? Which version of Swift are you using? Which platform are you running on?

**Comment by arkeo01** [comment]
I am using swift 4.2 on ubuntu 18.04... 
And below is the swift package
`
import PackageDescription

var deps: [Package.Dependency] = [
	.package(url: "https://github.com/pixelspark/sqlite.git", from: Version("3.0.0")),
	.package(url: "https://github.com/pixelspark/postgres-wire-server.git", from: Version("1.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura.git", from: Version("1.0.2")), 
	.package(url: "https://github.com/jatoben/CommandLine.git", from: Version("3.0.0-pre1")),
	.package(url: "https://github.com/pixelspark/swift-parser-generator.git", from: Version("2.0.2")),
	.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: Version("1.7.1")),
	.package(url: "https://github.com/vzsg/ed25519.git", from: Version("0.2.0")),
	.package(url: "https://github.com/pixelspark/base58.git", from: Version("1.0.0")),
	.package(url: "https://github.com/Bouke/NetService.git", from: Version("0.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura-WebSocket", from: Version("1.0.0")),
]

var ccDeps: [Target.Dependency] = [
	"SQLite",
	"Ed25519",
	"Base58",
	"HeliumLogger",
	"Kitura",
	"Kitura-WebSocket",
	"NetService"
]

#if !os(Linux)
	// Starscream is used for outgoing WebSocket connections; unfortunately it is not available on Linux
	deps.append(.package(url: "https://github.com/daltoniam/Starscream.git", from: Version("3.0.0")))
	ccDeps.append("Starscream")
#endif

let package = Package(
    name: "Catena",

    products: [
		.library(
			name: "CatenaCore",
			type: .static,
			targets: ["CatenaCore"]
		),
		.library(
			name: "CatenaSQL",
			type: .static,
			targets: ["CatenaSQL"]
		),
		.executable(name: "Catena", targets: ["Catena"]),
	],

    dependencies: deps,

    targets: [
		.testTarget(name: "CatenaTests", dependencies: ["CatenaCore"]),
		.testTarget(name: "CatenaSQLTests", dependencies: ["CatenaSQL"]),
		.target(
			name: "Catena",
			dependencies: [
				"CatenaCore",
				"CatenaSQL",
				"CommandLine"
			]
		),
		.target(
			name: "CatenaSQL",
			dependencies: [
				"CatenaCore",
				"SwiftParser",
				"PostgresWireServer"
			]
		),
		.target(
			name: "CatenaCore",
			dependencies: ccDeps
		)
	]
)

`

**Comment by ianpartridge** [comment]
Kitura 1 does not support Swift 4.2, so you will need to move up to Kitura 2 before we can start looking into your problems I'm afraid.

**Comment by ianpartridge** [comment]
Are you on the Kitura Slack? Please post there and we can help. I'm closing this issue as it's not related to the `OpenSSL` package.
